-- Tile Catalog Supabase schema
-- Run this file in Supabase SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.products (
  id text primary key,
  code text,
  name text not null,
  image text,
  size text,
  surface text,
  origin text,
  color text,
  price text,
  pdf text,
  description text,
  category text,
  qr_link text,
  gallery text,
  video text,
  collection text,
  drive_image_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text,
  created_at timestamptz not null default now()
);

create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  product_id text,
  product_name text,
  code text,
  customer_name text,
  phone text,
  note text,
  source text,
  status text not null default 'NEW'
);

create table if not exists public.product_views (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  product_id text,
  product_name text,
  code text,
  source text
);

create index if not exists products_name_idx on public.products (name);
create index if not exists products_code_idx on public.products (code);
create index if not exists leads_created_at_idx on public.leads (created_at desc);
create index if not exists product_views_created_at_idx on public.product_views (created_at desc);
create index if not exists product_views_product_id_idx on public.product_views (product_id);

alter table public.products enable row level security;
alter table public.admins enable row level security;
alter table public.leads enable row level security;
alter table public.product_views enable row level security;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.admins
    where user_id = auth.uid()
  );
$$;

drop policy if exists "Public can read products" on public.products;
create policy "Public can read products"
on public.products for select
using (true);

drop policy if exists "Admins can insert products" on public.products;
create policy "Admins can insert products"
on public.products for insert
with check (public.is_admin());

drop policy if exists "Admins can update products" on public.products;
create policy "Admins can update products"
on public.products for update
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admins can delete products" on public.products;
create policy "Admins can delete products"
on public.products for delete
using (public.is_admin());

drop policy if exists "Users can read own admin row" on public.admins;
create policy "Users can read own admin row"
on public.admins for select
using (user_id = auth.uid());

drop policy if exists "Public can create leads" on public.leads;
create policy "Public can create leads"
on public.leads for insert
with check (true);

drop policy if exists "Admins can read leads" on public.leads;
create policy "Admins can read leads"
on public.leads for select
using (public.is_admin());

drop policy if exists "Public can create product views" on public.product_views;
create policy "Public can create product views"
on public.product_views for insert
with check (true);

drop policy if exists "Admins can read product views" on public.product_views;
create policy "Admins can read product views"
on public.product_views for select
using (public.is_admin());

insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do update set public = excluded.public;

drop policy if exists "Public can read product images" on storage.objects;
create policy "Public can read product images"
on storage.objects for select
using (bucket_id = 'product-images');

drop policy if exists "Admins can upload product images" on storage.objects;
create policy "Admins can upload product images"
on storage.objects for insert
with check (
  bucket_id = 'product-images'
  and public.is_admin()
);

drop policy if exists "Admins can update product images" on storage.objects;
create policy "Admins can update product images"
on storage.objects for update
using (
  bucket_id = 'product-images'
  and public.is_admin()
)
with check (
  bucket_id = 'product-images'
  and public.is_admin()
);

drop policy if exists "Admins can delete product images" on storage.objects;
create policy "Admins can delete product images"
on storage.objects for delete
using (
  bucket_id = 'product-images'
  and public.is_admin()
);

-- After creating an admin user in Supabase Auth, run this with that user's id/email:
-- insert into public.admins (user_id, email)
-- values ('00000000-0000-0000-0000-000000000000', 'admin@example.com')
-- on conflict (user_id) do update set email = excluded.email;
